-- CreateTable
CREATE TABLE "Information" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "cover" STRING NOT NULL,
    "sinopsis" STRING NOT NULL,

    CONSTRAINT "Information_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Shows" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "starts" STRING NOT NULL,
    "ends" STRING NOT NULL,
    "showId" INT4 NOT NULL,

    CONSTRAINT "Shows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Day" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "day" STRING NOT NULL,

    CONSTRAINT "Day_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_DayToShows" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Information_name_key" ON "Information"("name");

-- CreateIndex
CREATE UNIQUE INDEX "_DayToShows_AB_unique" ON "_DayToShows"("A", "B");

-- CreateIndex
CREATE INDEX "_DayToShows_B_index" ON "_DayToShows"("B");

-- AddForeignKey
ALTER TABLE "Shows" ADD CONSTRAINT "Shows_showId_fkey" FOREIGN KEY ("showId") REFERENCES "Information"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_DayToShows" ADD CONSTRAINT "_DayToShows_A_fkey" FOREIGN KEY ("A") REFERENCES "Day"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_DayToShows" ADD CONSTRAINT "_DayToShows_B_fkey" FOREIGN KEY ("B") REFERENCES "Shows"("id") ON DELETE CASCADE ON UPDATE CASCADE;
