export const horarios = [
  {
    lunes: [
      {
        id: '1',
        name: 'Virtua Fighter',
        start: '00:00',
        ending: '00:30',
      },
      {
        id: '2',
        name: "B't X",
        start: '00:30',
        ending: '01:00',
      },
      {
        id: '3',
        name: 'Evangelion',
        start: '01:00',
        ending: '01:30',
      },
      {
        id: '4',
        name: 'Cowboy Bebop',
        start: '01:30',
        ending: '02:00',
      },
      {
        id: '5',
        name: "Wolf's Rain",
        start: '02:00',
        ending: '02:30',
      },
      {
        id: '6',
        name: 'Nadesico',
        start: '02:30',
        ending: '03:00',
      },
      {
        id: '7',
        name: 'Bob y Margaret',
        start: '03:00',
        ending: '03:30',
      },
      {
        id: '8',
        name: 'Daria',
        start: '03:30',
        ending: '04:00',
      },
      {
        id: '9',
        name: 'Lost Universe',
        start: '04:00',
        ending: '04:30',
      },
      {
        id: '10',
        name: 'Those Who Hunt Elves',
        start: '04:30',
        ending: '05:00',
      },
      {
        id: '11',
        name: 'Evangelion',
        start: '05:00',
        ending: '05:30',
      },
      {
        id: '12',
        name: 'Cowboy Bebop',
        start: '05:30',
        ending: '06:00',
      },
      {
        id: '13',
        name: 'Soul Hunter',
        start: '06:00',
        ending: '06:30',
      },
      {
        id: '14',
        name: 'Blue Seed',
        start: '06:30',
        ending: '07:00',
      },
      {
        id: '15',
        name: 'Lupin III',
        start: '07:00',
        ending: '07:30',
      },
      {
        id: '16',
        name: 'El Baron Rojo',
        start: '07:30',
        ending: '08:00',
      },
      {
        id: '17',
        name: 'Virtua Fighter',
        start: '08:00',
        ending: '08:30',
      },
      {
        id: '18',
        name: "B't X",
        start: '08:30',
        ending: '09:00',
      },
      {
        id: '19',
        name: 'Visionaries',
        start: '09:00',
        ending: '09:30',
      },
      {
        id: '20',
        name: 'Flash Gordon',
        start: '09:30',
        ending: '10:00',
      },
      {
        id: '21',
        name: 'Rambo',
        start: '10:00',
        ending: '10:30',
      },
      {
        id: '22',
        name: 'Rambo',
        start: '10:30',
        ending: '11:00',
      },
      {
        id: '23',
        name: 'Thundercats',
        start: '11:00',
        ending: '11:30',
      },
      {
        id: '24',
        name: 'Thundercats',
        start: '11:30',
        ending: '12:00',
      },
      {
        id: '25',
        name: 'Ren y Stimpy',
        start: '12:00',
        ending: '12:30',
      },
      {
        id: '26',
        name: 'Casa de Mutantes',
        start: '12:30',
        ending: '13:00',
      },
      {
        id: '27',
        name: 'The Critic',
        start: '13:00',
        ending: '13:30',
      },
      {
        id: '28',
        name: 'Duckman',
        start: '13:30',
        ending: '14:00',
      },
      {
        id: '29',
        name: 'Las Guerreras Magicas',
        start: '14:00',
        ending: '14:30',
      },
      {
        id: '30',
        name: 'The Vision of Escaflowne',
        start: '14:30',
        ending: '15:00',
      },
      {
        id: '31',
        name: 'Animafilms',
        start: '15:30',
        ending: '17:00',
      },
      {
        id: '32',
        name: 'He-Man',
        start: '17:00',
        ending: '17:30',
      },
      {
        id: '33',
        name: 'Los defensores de la tierra',
        start: '17:30',
        ending: '18:00',
      },
      {
        id: '34',
        name: "Wolf's Rain",
        start: '18:00',
        ending: '18:30',
      },
      {
        id: '35',
        name: 'Nadesico',
        start: '18:30',
        ending: '19:00',
      },
      {
        id: '36',
        name: 'Bob y Margaret',
        start: '19:00',
        ending: '19:30',
      },
      {
        id: '37',
        name: 'Daria',
        start: '19:30',
        ending: '20:00',
      },
      {
        id: '38',
        name: 'Lost Universe',
        start: '20:00',
        ending: '20:30',
      },
      {
        id: '39',
        name: 'Those Who Hunt Elves',
        start: '20:30',
        ending: '21:00',
      },
      {
        id: '40',
        name: 'Evangelion',
        start: '21:00',
        ending: '21:30',
      },
      {
        id: '41',
        name: 'Cowboy Bebop',
        start: '21:30',
        ending: '22:00',
      },
      {
        id: '42',
        name: 'Soul Hunter',
        start: '22:00',
        ending: '22:30',
      },
      {
        id: '43',
        name: 'Blue Seed',
        start: '22:30',
        ending: '23:00',
      },
      {
        id: '44',
        name: 'Lupin III',
        start: '23:00',
        ending: '23:30',
      },
      {
        id: '45',
        name: 'El Baron Rojo',
        start: '23:30',
        ending: '00:00',
      },
    ],
    martes: [{ testeo: 'nani' }],
  },
];

export default function handler(req, res) {
  // Get data from your database
  res.status(200).json(horarios);
}
